import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { Manrope } from "next/font/google";
import { Toaster } from "@/components/atoms/sonner";
import "./globals.css";

const manropeSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manropeSans.className} antialiased`}>
        <StackProvider app={stackClientApp}>
          <StackTheme>
            {children}
            <Toaster duration={100000} />
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
